#!/bin/bash
#Auth:fangwenjun
#E-mail:admin@fangwenjun.com
#Date:2016-03-20
username='admin/file201503'
password='513341aaqq@#'
local_dir='/root/back'
remote_dir='/backup/'
backup_dir='/www/fangwenjun.com'

tar cvf ${local_dir}`date '+%Y%m%d'.tar.gz` ${backup_dir}

ftp -v -n v0.ftp.upyun.com <<END
user ${username} ${password}
binary
hash
cd ${remote_dir}
lcd ${local_dir}
prompt
mput `date '+%Y%m%d'.tar.gz`
bye
END
